links.md

Small typos

---

guide.md

**sdX** is the disk that Qubes OS will be installed on
**sdY** is the USB that will contain the bootloader and the detached LUKS header file
**sdZ** is the USB stick containing the Qubes OS installer
Prepare your disk by first overwriting with random data
`dd if=/dev/urandom of=/dev/sdX status=progress`
`dd if=/dev/zero of=header.img bs=16M count=1`
`cryptsetup luksFormat /dev/sdX --header header.img`
`cryptsetup luksOpen /dev/sdX luks --header header.img`
```pvcreate /dev/mapper/luks
vgcreate qubes_dom0 /dev/mapper/luks
lvcreate -n swap -L 10G qubes_dom0
lvcreate -T -L 60G qubes_dom0/root-pool
lvcreate -T -l +100%FREE qubes_dom0/vm-pool
lvcreate -V60G -T qubes_dom0/root-pool -n root
lvcreate -V871G -T qubes_dom0/vm-pool -n vm
mkfs.ext4 /dev/qubes_dom0/vm 
```
```
mkfs.ext4 …
```

[WIP] Update Qubes route for 4.1.x

---

guide.md

CTemplar: removing all refs to it because it shutdown

---

guide.md

Proton: fixing links, refs, redirects and archive urls

---

guide.md

Fixing warning and link to libredirect

---

guide.md

https://positive.security/blog/video-depixelation

Added link to article about depixelization/deblurring of videos

---

guide.md

Just a month change may > june

Just a month change may > june

---

guide.md

Fix to issue #39 with the missing ODT

Fix to issue #39 with the missing ODT

---

guide.md

- notify that the dark pdf is no longer available
- notify that thet ODT is temporarily unavailable
- removal of the IPFS mirror

Small updates to content listing

---

CHANGELOG.md

Update changelog to reflect current situation

Update changelog to reflect current situation

---

guide.md

> **Warning**: Berty is still under active development and should not be used to exchange important data.
> "Berty is an open, secure, offline-first, peer-to-peer and zero trust messaging app."
Berty is an anonymous, secure, peer-to-peer protocol that doesn’t need an internet connection to function.
- No phone number or email required to create an account
- End-to-end encryption (E2EE) used to encrypt all conversations
- Focus on leaking as little metadata as possible
- Decentralized, distributed, serverless
- No consensus, no blockchain
- No internet connection required (uses the [BLE technology ](https://en.wikipedia.org/wiki/Bluetooth_Low_Energy)and mDNS)
- Free forever, no data stored, transparent code, open-source
1. Generate Account ID Key Pair. This operation will not be repeated. …

Adding berty messenger

---

_layouts/default.html

This PR will not conflict with the 1.1.5 update and can be applied immediately
It will re-add the twitter button on the top menu
See isssue #84

Re-introduction of the Twitter button (no conflct with 1.1.5 update)

---

guide.md

Fixed the collated "we" (hopefully not missing any, and there were many)
Reverted some that should have stayed "I" in references
Fixed grammar "I am" > "We are" and so on...

Fixed (hopefully) all the "we" and reverted some

---

_layouts/default.html

(Urgent) Bump to 1.1.5

---

guide.md

Fixed ref 294

---

CHANGELOG.md

Small grammar fixes changelog

---

.gitignore
README.md
briar.md
guide.md

README / Ukrainian info update and fixes

README / Ukrainian info update and fixes

---

README.md
guide.md

Small README updates.
And first part of an update to the evil-maid, tampering and OPSEC sections. Mostly separating OPSEC into Digital/Online and Physical tips.
Added a disclaimer to the potential risks of preventing (not just detecting) an evil-maid et small changes into the tampering sections

Small README updates

---

guide.md

Small references quick  fixes

---

guide.md

Fix an errant white space before comma and typo in "guide"

guide: fix comma in 2 lines

---

guide.md

This one stood right out to me, skimming the document.

guide: fix random newline that breaks a sentence

---

guide.md

Evil-Maid Attack section needed a reference to Anti Evil Maid section, and the pointer was missing.

guide: fix missing pointer for Anti Evil Maid

---

guide.md

Add TR & TE explanation to Appendix V1: Hardening your Browsers.

guide: Tracking Reduction and Tracking Evasion

---

guide.md

A quick note about correlation and attribution.

guide: note about Correlation vs Attribution of activities

---

guide.md

guide: add additional OPSEC notes

---

guide.md

Adding link to "Microarchitectural Side-channel Deanonymization Attacks:" warning in each route

Adding link to the side-channel attack in each route

---

guide.md

Replace section "When using BTC: bonus step for improving your privacy using obfuscation" with appropriate recommendation. 
Warning issued instead.
See #154
Academic References provided.

Replacement of "When using BTC: bonus ..." section

---

guide.md

Add ref to a very insightful DEF CON 25 vid about fingerprinting in various sections

Add ref to a DEF CON 25 vid about fingerprinting

---

guide.md

Added: https://abrahamjuliot.github.io/creepjs/
Fixed: fixed some typos

Add item in listing of sites showing your browser fingerprint and fixing typos

---

guide.md

Update Windows 10/11 VM links in ToC and addon recommendations in document
Fixes: #165

Fix Windows 10/11 links and update browser addons

---

guide.md

Added link to https://github.com/Qubes-Community/Contents/blob/master/docs/os/windows/windows-tools41.md

Link to Qubes tutorial for installing Windows VMs

---

_config.yml

Update to social links for SEO plugin

Update to social links for SEO plugin

---

guide.md

Couple of "we" typos

---

links.md

Small fix anonymousplanet.org , added -ng

Small fix on Links page , anonymousplanet.org , added -ng

---

CONTRIBUTING.md
guide.md

Update of bad links from old repo to org repo

Update of bad links from old repo to org repo

---

guide.md

Added links to recommended VPNs logging policies in Appendix G

Adding recommended VPNs logging policies links

---

guide.md

Added link to Appendix A4 to countering forensics linguistic analysis 
https://seirdy.one/posts/2022/07/09/stylometric-fingerprinting-redux/

Added link to countering linguistic analysis

---

README.md
_config.yml
guide.md

Adding Tor Mirror URL to readme and guide

Add tor mirror url to readme and guide

---

guide.md

Removed outdated info
Added ref to updated info

Small fix in the "pay with crypto section"

---

about.md

Fixed wrong e-mail on about page

Fixed wrong e-mail on about page 

---

chatrooms-rules.md

Update chatroom rules to add #OSINT

Update (current) chatroom rules to add #OSINT

---

guide.md

Update bad link Appendix R

---

guide.md

Adding mention of OSINT room in guide

Adding mention of OSINT room in guide

---

guide.md

Fix bad links to VPN logging policies from https://github.com/Anon-Planet/thgtoa/commit/305c4b9150cca

Fix bad links to VPN logging policies

---

guide.md

This fixes an indentation issue which renders as a code block instead.

Fix minor formatting issue

---

guide.md

Adding removed delimiter

---

guide.md

Adding link to video endorsed by LINDDUN designers

Adding link to an endorsed LINDDUN video

---

guide.md

- Mentioning those that are outdated/unmaintained and that those will be removed in next releases
- Adding https://github.com/bkil/secuchart which is a  maintained project
- Adding disclaimer that we do not necessarily endorse their opinions
- Removed spaces between list items (and we should consider doing that on the whole guide)

Update to other messaging apps comparisons charts

---

verify.md

Small changed here and there, addition of the Dangerzone tool.

Small changes here and there

---

README.md

Cleanup links in the README.md to inline links as used in the guide.

Cleanup README file links

---

.gitignore

It probably doesn't need to be so long, let's cleanup a bit.

Minimize .gitignore file

---

.github/ISSUE_TEMPLATE/documentation.md

Fix a typo introduced by my PR for issue templates.

Fix typo in issue template

---

verify.md

Small suggestions

---

guide.md

Update some of the settings that have changed since. Also add filter lists.

Update Appendix V1 regarding Brave Browser settings

---

donations.md

Added my donation for the VPS upgrade

Added my donation for the VPS upgrade

---

guide.md

Small useless content deletion
Feel free to merge directly

Small useless content deletion

---

guide.md

Adding quick LINDDUN tutorial video link for getting started. The video has been reviewed positively by LINDDUN designers/researchers on our demand.

Adding (reviewed/approved by LINDDUN designers) quick tutorial video link

---

guide.md

The ToC item is missing and the links in other sections aren't redirecting properly. Might not be the only one we missed from the removal of redirects.

Fix Gait Recognition and Other Long-Range Biometrics

---

guide.md

You can still be caught out by some identifiers in a VM. (#252)

Note these factors when using nested virtualization.

---

.github/workflows/mirror.yml

This updates the workflows directory:
- adding repository mirroring

Update workflow for mirroring

---

links.md

<https://AnarSec.guide> is a valuable resource with similar content to Anonymous Planet's THGTOA. I have been in contact with them for a bit, and would like to list them under our [Links to other notable projects](https://anonymousplanet.org/links.html). They seem very well-informed, and they appear to be "old-school", ASCII art and all. Please look at their series on the Qubes OS and Tails Linux distributions.

add AnarSec to links

---

verify.md

build: fix automatic VT scans

---

guide.md

remove this period as it messes with the markdown refs

appendix d: remove trailing period in title

---

.github/workflows/lock-threads.yml
CHANGELOG.md
_layouts/default.html
guide.md

Any threads, which have had no updates/activity in 180 days, will be closed and labeled as archived and outdated.

chore: lock old issues & pull requests

---

guide.md

Reverts Anon-Planet/thgtoa#305
Needs more research, better grammar and probably won't be something I work on considering feedback.
I'm not a cryptographer, I just worked on cryptographic systems.

Revert "Quantum resistance and good crypto algos"

---

guide.md

Some options need to be updated as they have moved from one place to another.

Fixup Brave config settings

---

guide.md

Update "Online Phone Number" section
As always, this guide recommends using providers which accept Monero (XMR) as payment, or, at the very least offer non-KYC transaction via BTC - which is viable using this guide.
Do not trust Google results for "free SMS verification".

Add silent.link to Online Phone Number section

---

CONTRIBUTING.md

Change "master" branch to "main" reference in CONTRIBUTING.md

Change "master" branch to "main"

---

.github/FUNDING.yml
.github/ISSUE_TEMPLATE/build.yml
.github/ISSUE_TEMPLATE/config.yml
.github/pull_request_template.md
.github/release-drafter.yml
.github/workflows/depends.yml
.github/workflows/lock-threads.yml
.github/workflows/prettier_md.yml
.github/workflows/release-drafter.yml
.github/workflows/vt-scan.yml

Fixes #329 and drastically improves QOL for repo maintainers.
All releases are drafted as PRs are merged to `main` branch.
Keep all PR titles short, they will be included in the release draft.

Add Action files and stage PR

---

guide.md

Opsec Links addition see issue #340

Opsec Links addition see #340
